name: Lengua
description: The best way to learn and master Spanish grammar.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth:
  google_sign_in:
  cloud_firestore: ^0.7.4
  font_awesome_flutter: ^7.1.0
  icons_helper: ^0.0.7
  flutter_launcher_icons: ^0.6.1
  animated_background: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path:  "/Users/daniilgrodskiy/Desktop/FlutterApps/spanish_grammar_app_flutter/assets/lengua_app_icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/spanish_flag.png
   - assets/google_sign_in.png
   - assets/wallpaper.jpg
   - assets/test_background.png
   - assets/general_topics_backgrounds/generalTopicsBackground.png
   - assets/confetti.png

  
  


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: avenir-next
      fonts:
        - asset: assets/avenir-next-regular.ttf
    - family: concert-one
      fonts:
        - asset: assets/concert-one-regular.ttf
    - family: viga
      fonts:
        - asset: assets/viga-regular.ttf


  #     
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
